tuna:
  controller_manager:
    ros__parameters:
      update_rate: 50

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      diff_drive_controller:
       type: diff_drive_controller/DiffDriveController

      # left_thruster_controller:  
      #   type: forward_command_controller/ForwardCommandController 

      # right_thruster_controller:  
      #   type: forward_command_controller/ForwardCommandController 



  diff_drive_controller:
    ros__parameters:
      left_wheel_names: ["base_to_dummy_prop_left"]
      right_wheel_names: ["base_to_dummy_prop_right"]

      wheel_separation: 0.036
      wheel_radius: 0.009

      odom_frame_id: "odom"
      base_frame_id: "base_link"

      pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
      twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

      enable_odom_tf: true
      publish_rate: 50.0
      
      linear.x.max_velocity: 1.0
      linear.x.min_velocity: -1.0
      angular.z.max_velocity: 1.0
      angular.z.min_velocity: -1.0




  # left_thruster_controller:  
  #   ros__parameters:
  #     joints: 
  #       - 'base_to_dummy_prop_left'
  #     interface_name: velocity 

  # right_thruster_controller:  
  #   ros__parameters:
  #     joints: 
  #       - 'base_to_dummy_prop_right'
  #     interface_name: velocity 